In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## Extract Year

In [9]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
775 2019-05-27        5968       13      11       2019
291 2018-11-20        5009       28      12       2018
697 2019-10-10        3582       26       2       2019
475 2019-07-25        2898       18      98       2019
828 2019-04-22        6933       25      43       2019

In [10]:
date['date_mounth'] = date['date'].dt.month

date.sample(5)

          date  product_id  city_id  orders  date_year  date_mounth
747 2018-08-06        2490        7       9       2018            8
46  2018-09-23        2815       13       1       2018            9
290 2018-12-05        4254       16      37       2018           12
647 2018-09-05        6556       23       2       2018            9
830 2019-03-14        3047        4       4       2019            3

In [11]:
# for month name 
date['date_mounth_name'] = date['date'].dt.month_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_mounth,date_mounth_name
810,2019-06-25,1187,2,45,2019,6,June
372,2019-03-05,6933,25,34,2019,3,March
446,2019-06-28,5430,14,7,2019,6,June
839,2018-09-23,5284,25,1,2018,9,September
149,2019-02-09,1024,10,2,2019,2,February

In [12]:
date['date_day'] = date['date'].dt.day

date.sample(5)

,date,product_id,city_id,orders,date_year,date_mounth,date_mounth_name,date_day
302,2018-10-05,2012,8,32,2018,10,October,5
636,2018-11-01,1744,13,4,2018,11,November,1
64,2019-06-01,3541,2,5,2019,6,June,1
134,2019-11-17,6049,16,1,2019,11,November,17
416,2019-08-02,664,24,1,2019,8,August,2

In [13]:
# day of Week
date['date_dow'] = date['date'].dt.dayofweek

date.sample(5)

,date,product_id,city_id,orders,date_year,date_mounth,date_mounth_name,date_day,date_dow
355,2019-09-18,6779,10,3,2019,9,September,18,2
738,2019-05-27,7585,27,2,2019,5,May,27,0
260,2019-02-04,4483,25,1,2019,2,February,4,0
723,2018-12-07,2879,3,1,2018,12,December,7,4
215,2018-11-01,7266,19,4,2018,11,November,1,3

In [14]:
date['date_dow_name'] = date['date'].dt.day_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_mounth,date_mounth_name,date_day,date_dow,date_dow_name
566,2019-04-29,3646,14,63,2019,4,April,29,0,Monday
731,2019-04-23,2598,0,6,2019,4,April,23,1,Tuesday
619,2018-09-24,7450,21,4,2018,9,September,24,0,Monday
428,2018-07-14,4183,22,8,2018,7,July,14,5,Saturday
588,2019-05-21,3055,6,1,2019,5,May,21,1,Tuesday

In [15]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_mounth,date_mounth_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

## Extract week of the year

In [18]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_mounth,date_mounth_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

## Extract Quater

In [19]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_mounth,date_mounth_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

## Extract Semester

In [20]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_mounth,date_mounth_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

## Extract Time elapsed between dates

In [21]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 4, 4, 8, 39, 44, 735841)

In [22]:
today - date['date']

0     2307 days 08:39:44.735841
1     2789 days 08:39:44.735841
2     2720 days 08:39:44.735841
3     2422 days 08:39:44.735841
4     2645 days 08:39:44.735841
                 ...
995   2735 days 08:39:44.735841
996   2676 days 08:39:44.735841
997   2524 days 08:39:44.735841
998   2589 days 08:39:44.735841
999   2363 days 08:39:44.735841
Name: date, Length: 1000, dtype: timedelta64[ns]

In [23]:
(today - date['date']).dt.days

0      2307
1      2789
2      2720
3      2422
4      2645
       ...
995    2735
996    2676
997    2524
998    2589
999    2363
Name: date, Length: 1000, dtype: int64

In [25]:
# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'm'),0)

0      3322600.0
1      4016680.0
2      3917320.0
3      3488200.0
4      3809320.0
         ...
995    3938920.0
996    3853960.0
997    3635080.0
998    3728680.0
999    3403240.0
Name: date, Length: 1000, dtype: float64

In [27]:
time.sample(5)

                    date                                                msg
993  2015-07-23 23:02:00  Кривой Рог Парень27лет ищу стройную девушку дл...
938  2013-11-28 01:47:00           Парень31г ищу девушку для и/о 0968908998
626  2014-05-15 02:14:00               Ищу д. Для знаком до 35 лет. Мне 37.
864  2012-07-06 23:49:00                    парень ищет друга 099 927 13 80
48   2013-01-19 23:07:00  п 29 поз с дев  для встреч сейчас  0636501245 ...

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [29]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [30]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [31]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0